ARG BASE_IMAGE=fudannlp/fudannlp:pytorch1.9.0-cuda11.1-cudnn8-runtime-sshd-ceph

FROM ${BASE_IMAGE}

WORKDIR /tmp

COPY requirements.txt .

# BASE_IMAGE通过conda安装的python, 这里同样使用conda安装uwsgi，否则python lib的版本不匹配
RUN conda install -y icu=58
RUN conda install -y -c conda-forge python=3.7.0 uwsgi

RUN pip install --no-cache --ignore-installed \
                 -U pip setuptools

RUN pip install --no-cache --ignore-installed \
                 supervisor==4.2.2 \
                 click==7.1.2 \
                 label-studio-ml==1.0.3 \
                 -r requirements.txt

COPY uwsgi.ini /etc/uwsgi/
COPY supervisord.conf /etc/supervisor/conf.d/

WORKDIR /app

COPY . /app

EXPOSE 9090

ENV MODEL_DIR=/maas_storage/model

# 基础镜像中的CMD是启动sshd服务，这里将CMD注释掉以符合大家平时的使用习惯
#CMD ["/opt/conda/bin/label-studio-ml", "start", "/app" ]