ARG BASE_IMAGE=fudannlp/fudannlp:pytorch1.9.0-cuda11.1-cudnn8-runtime-sshd-ceph

FROM ${BASE_IMAGE}

WORKDIR /tmp

COPY requirements.txt .

# BASE_IMAGE通过conda安装的python, 这里同样使用conda安装uwsgi，否则python lib的版本不匹配
RUN conda install -y -c conda-forge uwsgi

RUN pip install \
                -r requirements.txt \
                supervisor==4.2.2 \
                click==7.1.2 \
                label-studio-ml==1.0.3

COPY uwsgi.ini /etc/uwsgi/
COPY supervisord.conf /etc/supervisor/conf.d/

WORKDIR /app

COPY . /app

EXPOSE 9090

ENV MODEL_DIR=/maas_storage/model

# 为了调试方便，把CMD改成一条dummy的命令
CMD ["sleep", "infinity"]
#CMD ["/opt/conda/bin/label-studio-ml", "start", "/app" ]